### ISSUE TITLE
about Updates.addListener

### ISSUE THREAD

**Issue by wangliguang** [Joshandrews43/useExpoUpdates#1]
I have two questions to ask？ thank you very much

1. Why not use it `Updates.addListener`?

2. How to ensure that the new bundle is downloaded at the `options.timeout` time?

**Comment by Joshandrews43** [comment]
> I have two questions to ask？ thank you very much
> 
> 1. Why not use it `Updates.addListener`?
> 2. How to ensure that the new bundle is downloaded at the `options.timeout` time?

I'm not sure if `Updates.addListener` works once the app is backgrounded, for a long time, as the OS may need to kill your process to free up memory. This is why I implemented it using `AppState`.

`options.timeout` is only used if you are updating on app launch if I am not mistaken. Since the function I create is `async`, once the updates are done downloading it will force the user to relaunch the app.

Feel free to make a pull request to add any additional features!
